---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project3-angular-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-deployment
  template:
    metadata:
      labels:
        app: angular-deployment
    spec:
      containers:
      - image: keoffor/angular:latest
        env:
          - name: VALIDATION
            value: http://34.122.231.247:8081/users/validate
          - name: EUREKA_URI
            value: http://35.223.118.158:8083/eureka
          - name: ANGULAR_URI
            value: http://34.122.103.73:80
        imagePullPolicy: Always
        name: angularcontainer
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-service
  name: angularservice
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http-angular
      port: 80
      targetPort: 80
  selector:
    app: angular-deployment








